# Generated by Django 4.0.4 on 2022-06-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchaseitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
