# Generated by Django 4.0.4 on 2022-05-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_saleitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
