# Generated by Django 4.0.4 on 2022-06-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='chekout',
            field=models.BooleanField(default=False),
        ),
    ]
