# Generated by Django 4.0.4 on 2022-06-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_sale_chekout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='chekout',
            new_name='checkout',
        ),
    ]
