# Generated by Django 4.0.4 on 2022-06-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='postal_code',
            field=models.PositiveIntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.PositiveIntegerField(max_length=8),
        ),
    ]
