# Generated by Django 4.0.4 on 2022-06-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_name_alter_billingaddress_postal_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
